/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDiscoveryRouteImport } from './routes/_authenticated/discovery'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedAgentActivityRouteImport } from './routes/_authenticated/agent-activity'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedRequirementsIndexRouteImport } from './routes/_authenticated/requirements/index'
import { Route as AuthenticatedRequirementsIdRouteImport } from './routes/_authenticated/requirements/$id'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDeliveriesIdRouteImport } from './routes/_authenticated/deliveries/$id'
import { Route as AuthenticatedProjectsIdIndexRouteImport } from './routes/_authenticated/projects/$id/index'
import { Route as AuthenticatedDeliveriesIdIndexRouteImport } from './routes/_authenticated/deliveries/$id/index'
import { Route as AuthenticatedProjectsIdTasksRouteImport } from './routes/_authenticated/projects/$id/tasks'
import { Route as AuthenticatedDeliveriesIdGateRouteImport } from './routes/_authenticated/deliveries/$id/gate'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoveryRoute = AuthenticatedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentActivityRoute =
  AuthenticatedAgentActivityRouteImport.update({
    id: '/agent-activity',
    path: '/agent-activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequirementsIndexRoute =
  AuthenticatedRequirementsIndexRouteImport.update({
    id: '/requirements/',
    path: '/requirements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequirementsIdRoute =
  AuthenticatedRequirementsIdRouteImport.update({
    id: '/requirements/$id',
    path: '/requirements/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveriesIdRoute =
  AuthenticatedDeliveriesIdRouteImport.update({
    id: '/deliveries/$id',
    path: '/deliveries/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdIndexRoute =
  AuthenticatedProjectsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any)
const AuthenticatedDeliveriesIdIndexRoute =
  AuthenticatedDeliveriesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeliveriesIdRoute,
  } as any)
const AuthenticatedProjectsIdTasksRoute =
  AuthenticatedProjectsIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any)
const AuthenticatedDeliveriesIdGateRoute =
  AuthenticatedDeliveriesIdGateRouteImport.update({
    id: '/gate',
    path: '/gate',
    getParentRoute: () => AuthenticatedDeliveriesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/agent-activity': typeof AuthenticatedAgentActivityRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/deliveries/$id': typeof AuthenticatedDeliveriesIdRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/requirements/$id': typeof AuthenticatedRequirementsIdRoute
  '/requirements/': typeof AuthenticatedRequirementsIndexRoute
  '/deliveries/$id/gate': typeof AuthenticatedDeliveriesIdGateRoute
  '/projects/$id/tasks': typeof AuthenticatedProjectsIdTasksRoute
  '/deliveries/$id/': typeof AuthenticatedDeliveriesIdIndexRoute
  '/projects/$id/': typeof AuthenticatedProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/agent-activity': typeof AuthenticatedAgentActivityRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/requirements/$id': typeof AuthenticatedRequirementsIdRoute
  '/requirements': typeof AuthenticatedRequirementsIndexRoute
  '/deliveries/$id/gate': typeof AuthenticatedDeliveriesIdGateRoute
  '/projects/$id/tasks': typeof AuthenticatedProjectsIdTasksRoute
  '/deliveries/$id': typeof AuthenticatedDeliveriesIdIndexRoute
  '/projects/$id': typeof AuthenticatedProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/agent-activity': typeof AuthenticatedAgentActivityRoute
  '/_authenticated/decisions': typeof AuthenticatedDecisionsRoute
  '/_authenticated/discovery': typeof AuthenticatedDiscoveryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/deliveries/$id': typeof AuthenticatedDeliveriesIdRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/_authenticated/requirements/$id': typeof AuthenticatedRequirementsIdRoute
  '/_authenticated/requirements/': typeof AuthenticatedRequirementsIndexRoute
  '/_authenticated/deliveries/$id/gate': typeof AuthenticatedDeliveriesIdGateRoute
  '/_authenticated/projects/$id/tasks': typeof AuthenticatedProjectsIdTasksRoute
  '/_authenticated/deliveries/$id/': typeof AuthenticatedDeliveriesIdIndexRoute
  '/_authenticated/projects/$id/': typeof AuthenticatedProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/agent-activity'
    | '/decisions'
    | '/discovery'
    | '/deliveries/$id'
    | '/errors/$error'
    | '/projects/$id'
    | '/requirements/$id'
    | '/requirements/'
    | '/deliveries/$id/gate'
    | '/projects/$id/tasks'
    | '/deliveries/$id/'
    | '/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/agent-activity'
    | '/decisions'
    | '/discovery'
    | '/'
    | '/errors/$error'
    | '/requirements/$id'
    | '/requirements'
    | '/deliveries/$id/gate'
    | '/projects/$id/tasks'
    | '/deliveries/$id'
    | '/projects/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/agent-activity'
    | '/_authenticated/decisions'
    | '/_authenticated/discovery'
    | '/_authenticated/'
    | '/_authenticated/deliveries/$id'
    | '/_authenticated/errors/$error'
    | '/_authenticated/projects/$id'
    | '/_authenticated/requirements/$id'
    | '/_authenticated/requirements/'
    | '/_authenticated/deliveries/$id/gate'
    | '/_authenticated/projects/$id/tasks'
    | '/_authenticated/deliveries/$id/'
    | '/_authenticated/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discovery': {
      id: '/_authenticated/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent-activity': {
      id: '/_authenticated/agent-activity'
      path: '/agent-activity'
      fullPath: '/agent-activity'
      preLoaderRoute: typeof AuthenticatedAgentActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requirements/': {
      id: '/_authenticated/requirements/'
      path: '/requirements'
      fullPath: '/requirements/'
      preLoaderRoute: typeof AuthenticatedRequirementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requirements/$id': {
      id: '/_authenticated/requirements/$id'
      path: '/requirements/$id'
      fullPath: '/requirements/$id'
      preLoaderRoute: typeof AuthenticatedRequirementsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries/$id': {
      id: '/_authenticated/deliveries/$id'
      path: '/deliveries/$id'
      fullPath: '/deliveries/$id'
      preLoaderRoute: typeof AuthenticatedDeliveriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/': {
      id: '/_authenticated/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AuthenticatedProjectsIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsIdRoute
    }
    '/_authenticated/deliveries/$id/': {
      id: '/_authenticated/deliveries/$id/'
      path: '/'
      fullPath: '/deliveries/$id/'
      preLoaderRoute: typeof AuthenticatedDeliveriesIdIndexRouteImport
      parentRoute: typeof AuthenticatedDeliveriesIdRoute
    }
    '/_authenticated/projects/$id/tasks': {
      id: '/_authenticated/projects/$id/tasks'
      path: '/tasks'
      fullPath: '/projects/$id/tasks'
      preLoaderRoute: typeof AuthenticatedProjectsIdTasksRouteImport
      parentRoute: typeof AuthenticatedProjectsIdRoute
    }
    '/_authenticated/deliveries/$id/gate': {
      id: '/_authenticated/deliveries/$id/gate'
      path: '/gate'
      fullPath: '/deliveries/$id/gate'
      preLoaderRoute: typeof AuthenticatedDeliveriesIdGateRouteImport
      parentRoute: typeof AuthenticatedDeliveriesIdRoute
    }
  }
}

interface AuthenticatedDeliveriesIdRouteChildren {
  AuthenticatedDeliveriesIdGateRoute: typeof AuthenticatedDeliveriesIdGateRoute
  AuthenticatedDeliveriesIdIndexRoute: typeof AuthenticatedDeliveriesIdIndexRoute
}

const AuthenticatedDeliveriesIdRouteChildren: AuthenticatedDeliveriesIdRouteChildren =
  {
    AuthenticatedDeliveriesIdGateRoute: AuthenticatedDeliveriesIdGateRoute,
    AuthenticatedDeliveriesIdIndexRoute: AuthenticatedDeliveriesIdIndexRoute,
  }

const AuthenticatedDeliveriesIdRouteWithChildren =
  AuthenticatedDeliveriesIdRoute._addFileChildren(
    AuthenticatedDeliveriesIdRouteChildren,
  )

interface AuthenticatedProjectsIdRouteChildren {
  AuthenticatedProjectsIdTasksRoute: typeof AuthenticatedProjectsIdTasksRoute
  AuthenticatedProjectsIdIndexRoute: typeof AuthenticatedProjectsIdIndexRoute
}

const AuthenticatedProjectsIdRouteChildren: AuthenticatedProjectsIdRouteChildren =
  {
    AuthenticatedProjectsIdTasksRoute: AuthenticatedProjectsIdTasksRoute,
    AuthenticatedProjectsIdIndexRoute: AuthenticatedProjectsIdIndexRoute,
  }

const AuthenticatedProjectsIdRouteWithChildren =
  AuthenticatedProjectsIdRoute._addFileChildren(
    AuthenticatedProjectsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentActivityRoute: typeof AuthenticatedAgentActivityRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRoute
  AuthenticatedDiscoveryRoute: typeof AuthenticatedDiscoveryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDeliveriesIdRoute: typeof AuthenticatedDeliveriesIdRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRouteWithChildren
  AuthenticatedRequirementsIdRoute: typeof AuthenticatedRequirementsIdRoute
  AuthenticatedRequirementsIndexRoute: typeof AuthenticatedRequirementsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentActivityRoute: AuthenticatedAgentActivityRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRoute,
  AuthenticatedDiscoveryRoute: AuthenticatedDiscoveryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDeliveriesIdRoute: AuthenticatedDeliveriesIdRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRouteWithChildren,
  AuthenticatedRequirementsIdRoute: AuthenticatedRequirementsIdRoute,
  AuthenticatedRequirementsIndexRoute: AuthenticatedRequirementsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
