ALTER TABLE deliveries ADD COLUMN parent_id UUID NULL REFERENCES deliveries(id);
ALTER TABLE deliveries ADD COLUMN wave INT NOT NULL DEFAULT 0;
ALTER TABLE deliveries ADD COLUMN split_mode BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE deliveries ADD COLUMN merge_state TEXT NOT NULL DEFAULT '';
